[package]
name = "bitgeon"
version = "0.1.0"
authors = ["Andy <19520383+LeCyberDucky@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
console = "0.10.1"
dialoguer = "0.5.1"
indicatif = "0.14.0"
crossbeam-channel = "0.4.2"
tui = { version = "0.9.1", default-features = false, features = ['crossterm'] }
